# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ggavriil/Programming/arm11_26/src/rpi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ggavriil/Programming/arm11_26/src/rpi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ggavriil/Programming/arm11_26/src/rpi/CMakeFiles /home/ggavriil/Programming/arm11_26/src/rpi/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ggavriil/Programming/arm11_26/src/rpi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rpi

# Build rule for target.
rpi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rpi
.PHONY : rpi

# fast build rule for target.
rpi/fast:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/build
.PHONY : rpi/fast

cstartup.obj: cstartup.c.obj

.PHONY : cstartup.obj

# target to build an object file
cstartup.c.obj:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/cstartup.c.obj
.PHONY : cstartup.c.obj

cstartup.i: cstartup.c.i

.PHONY : cstartup.i

# target to preprocess a source file
cstartup.c.i:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/cstartup.c.i
.PHONY : cstartup.c.i

cstartup.s: cstartup.c.s

.PHONY : cstartup.s

# target to generate assembly for a file
cstartup.c.s:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/cstartup.c.s
.PHONY : cstartup.c.s

cstubs.obj: cstubs.c.obj

.PHONY : cstubs.obj

# target to build an object file
cstubs.c.obj:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/cstubs.c.obj
.PHONY : cstubs.c.obj

cstubs.i: cstubs.c.i

.PHONY : cstubs.i

# target to preprocess a source file
cstubs.c.i:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/cstubs.c.i
.PHONY : cstubs.c.i

cstubs.s: cstubs.c.s

.PHONY : cstubs.s

# target to generate assembly for a file
cstubs.c.s:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/cstubs.c.s
.PHONY : cstubs.c.s

engine.obj: engine.c.obj

.PHONY : engine.obj

# target to build an object file
engine.c.obj:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/engine.c.obj
.PHONY : engine.c.obj

engine.i: engine.c.i

.PHONY : engine.i

# target to preprocess a source file
engine.c.i:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/engine.c.i
.PHONY : engine.c.i

engine.s: engine.c.s

.PHONY : engine.s

# target to generate assembly for a file
engine.c.s:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/engine.c.s
.PHONY : engine.c.s

game.obj: game.c.obj

.PHONY : game.obj

# target to build an object file
game.c.obj:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/game.c.obj
.PHONY : game.c.obj

game.i: game.c.i

.PHONY : game.i

# target to preprocess a source file
game.c.i:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/game.c.i
.PHONY : game.c.i

game.s: game.c.s

.PHONY : game.s

# target to generate assembly for a file
game.c.s:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/game.c.s
.PHONY : game.c.s

gamehelpers.obj: gamehelpers.c.obj

.PHONY : gamehelpers.obj

# target to build an object file
gamehelpers.c.obj:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/gamehelpers.c.obj
.PHONY : gamehelpers.c.obj

gamehelpers.i: gamehelpers.c.i

.PHONY : gamehelpers.i

# target to preprocess a source file
gamehelpers.c.i:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/gamehelpers.c.i
.PHONY : gamehelpers.c.i

gamehelpers.s: gamehelpers.c.s

.PHONY : gamehelpers.s

# target to generate assembly for a file
gamehelpers.c.s:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/gamehelpers.c.s
.PHONY : gamehelpers.c.s

graphics.obj: graphics.c.obj

.PHONY : graphics.obj

# target to build an object file
graphics.c.obj:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/graphics.c.obj
.PHONY : graphics.c.obj

graphics.i: graphics.c.i

.PHONY : graphics.i

# target to preprocess a source file
graphics.c.i:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/graphics.c.i
.PHONY : graphics.c.i

graphics.s: graphics.c.s

.PHONY : graphics.s

# target to generate assembly for a file
graphics.c.s:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/graphics.c.s
.PHONY : graphics.c.s

mailbox.obj: mailbox.c.obj

.PHONY : mailbox.obj

# target to build an object file
mailbox.c.obj:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/mailbox.c.obj
.PHONY : mailbox.c.obj

mailbox.i: mailbox.c.i

.PHONY : mailbox.i

# target to preprocess a source file
mailbox.c.i:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/mailbox.c.i
.PHONY : mailbox.c.i

mailbox.s: mailbox.c.s

.PHONY : mailbox.s

# target to generate assembly for a file
mailbox.c.s:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/mailbox.c.s
.PHONY : mailbox.c.s

main.obj: main.c.obj

.PHONY : main.obj

# target to build an object file
main.c.obj:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/main.c.obj
.PHONY : main.c.obj

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/main.c.s
.PHONY : main.c.s

physics.obj: physics.c.obj

.PHONY : physics.obj

# target to build an object file
physics.c.obj:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/physics.c.obj
.PHONY : physics.c.obj

physics.i: physics.c.i

.PHONY : physics.i

# target to preprocess a source file
physics.c.i:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/physics.c.i
.PHONY : physics.c.i

physics.s: physics.c.s

.PHONY : physics.s

# target to generate assembly for a file
physics.c.s:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/physics.c.s
.PHONY : physics.c.s

start.obj: start.s.obj

.PHONY : start.obj

# target to build an object file
start.s.obj:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/start.s.obj
.PHONY : start.s.obj

timer.obj: timer.c.obj

.PHONY : timer.obj

# target to build an object file
timer.c.obj:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/timer.c.obj
.PHONY : timer.c.obj

timer.i: timer.c.i

.PHONY : timer.i

# target to preprocess a source file
timer.c.i:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/timer.c.i
.PHONY : timer.c.i

timer.s: timer.c.s

.PHONY : timer.s

# target to generate assembly for a file
timer.c.s:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/timer.c.s
.PHONY : timer.c.s

uart.obj: uart.c.obj

.PHONY : uart.obj

# target to build an object file
uart.c.obj:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/uart.c.obj
.PHONY : uart.c.obj

uart.i: uart.c.i

.PHONY : uart.i

# target to preprocess a source file
uart.c.i:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/uart.c.i
.PHONY : uart.c.i

uart.s: uart.c.s

.PHONY : uart.s

# target to generate assembly for a file
uart.c.s:
	$(MAKE) -f CMakeFiles/rpi.dir/build.make CMakeFiles/rpi.dir/uart.c.s
.PHONY : uart.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rpi"
	@echo "... cstartup.obj"
	@echo "... cstartup.i"
	@echo "... cstartup.s"
	@echo "... cstubs.obj"
	@echo "... cstubs.i"
	@echo "... cstubs.s"
	@echo "... engine.obj"
	@echo "... engine.i"
	@echo "... engine.s"
	@echo "... game.obj"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... gamehelpers.obj"
	@echo "... gamehelpers.i"
	@echo "... gamehelpers.s"
	@echo "... graphics.obj"
	@echo "... graphics.i"
	@echo "... graphics.s"
	@echo "... mailbox.obj"
	@echo "... mailbox.i"
	@echo "... mailbox.s"
	@echo "... main.obj"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... physics.obj"
	@echo "... physics.i"
	@echo "... physics.s"
	@echo "... start.obj"
	@echo "... timer.obj"
	@echo "... timer.i"
	@echo "... timer.s"
	@echo "... uart.obj"
	@echo "... uart.i"
	@echo "... uart.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

